name: projects/meera-demos/locations/global/dataAgents/gda-731cca2e-0d1b-41bb-8fe0-e2c105208826
display_name: DSG Financial Agent
description: DSG Financial Agent (evaluates sales performance, revenue, store metrics,
  and inventory value)
create_time: '2026-06-28T14:23:50.670328974Z'
update_time: '2026-06-28T14:23:50.670328974Z'
labels: {}
