name: projects/meera-demos/locations/global/dataAgents/gda-13b505cd-5cf9-414b-ba5f-da162d90cb10
display_name: DSG Enhanced VIP Customer Agent
description: DSG Enhanced VIP Customer Agent (with Spanner Property Graph)
create_time: '2026-06-28T14:24:30.760468297Z'
update_time: '2026-06-28T14:24:30.760468297Z'
labels: {}
