dsg_products:
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: meera-demos
      dataset: dsg_products
      location: us-central1
      threads: 4
      timeout_seconds: 300
  target: dev
